services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/rifki-rchman/resep-nusantara
    branch: main
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
    buildCommand: |
      cp .env.example .env
      composer install --no-dev
      php artisan key:generate
      php artisan migrate
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
